#!/usr/bin/env python3
"""Generate src/boot/font-spleen.h for the patched sd-boot from a Spleen BDF.

Emits an 8x16 bitmap table for ASCII 0x20..0x7E plus a replacement glyph. The
renderer upscales by an integer factor, so one size covers every display.
"""
import re
import sys

FIRST, LAST = 0x20, 0x7E


def parse_bdf(path):
    glyphs = {}
    fbb = None
    enc = bbx = None
    bits = None
    for line in open(path, encoding="latin-1"):
        line = line.rstrip("\n")
        if line.startswith("FONTBOUNDINGBOX"):
            fbb = [int(x) for x in line.split()[1:5]]
        elif line.startswith("ENCODING"):
            enc = int(line.split()[1])
        elif line.startswith("BBX"):
            bbx = [int(x) for x in line.split()[1:5]]
        elif line == "BITMAP":
            bits = []
        elif line == "ENDCHAR":
            if enc is not None and bits is not None:
                glyphs[enc] = (bbx, bits)
            enc = bbx = bits = None
        elif bits is not None:
            bits.append(line.strip())
    return fbb, glyphs


def render(fbb, bbx, rows):
    """Place a BDF glyph bitmap into an fbb_w x fbb_h cell, row 0 = top."""
    fw, fh, fx, fy = fbb
    bw, bh, bx, by = bbx
    cell = [0] * fh
    # Cell row r holds y = (fy + fh - 1) - r; BDF row i holds y = by + bh - 1 - i.
    shift_y = (fy + fh) - (by + bh)
    shift_x = bx - fx
    for i, hexrow in enumerate(rows):
        r = i + shift_y
        if not 0 <= r < fh:
            continue
        # BDF pads each row to a whole number of bytes, MSB first.
        nbytes = (bw + 7) // 8
        val = int(hexrow, 16) if hexrow else 0
        val >>= (nbytes * 8 - bw)  # right-align to bw bits
        out = 0
        for c in range(bw):
            if val & (1 << (bw - 1 - c)):
                xc = c + shift_x
                if 0 <= xc < fw:
                    out |= 1 << (fw - 1 - xc)
        cell[r] |= out
    return cell


def main():
    bdf, out = sys.argv[1], sys.argv[2]
    fbb, glyphs = parse_bdf(bdf)
    fw, fh = fbb[0], fbb[1]
    if (fw, fh) != (8, 16):
        sys.exit(f"expected an 8x16 font, got {fw}x{fh}")

    lines = [
        "/* SPDX-License-Identifier: BSD-2-Clause */",
        "/* Generated by gen-font.py -- do not edit.",
        f" * Source: {bdf.split('/')[-1]} (Spleen, Copyright (c) 2018-2026, Frederic Cambus)",
        " */",
        "#pragma once",
        "",
        "#include \"efi.h\"",
        "",
        f"#define FONT_WIDTH {fw}",
        f"#define FONT_HEIGHT {fh}",
        f"#define FONT_FIRST_CHAR 0x{FIRST:02X}",
        f"#define FONT_LAST_CHAR 0x{LAST:02X}",
        "",
        "/* ASCII 0x20..0x7E, one byte per scanline, MSB = leftmost pixel. */",
        f"static const uint8_t font8x16[{LAST - FIRST + 1}][{fh}] = {{",
    ]
    missing = []
    for code in range(FIRST, LAST + 1):
        if code not in glyphs:
            missing.append(code)
            cell = [0] * fh
        else:
            cell = render(fbb, *glyphs[code])
        ch = chr(code).replace("\\", "\\\\").replace("*/", "")
        body = ", ".join(f"0x{b:02x}" for b in cell)
        lines.append(f"        {{ {body} }}, /* {ch!r} */")
    lines.append("};")
    lines += [
        "",
        "/* Drawn for anything outside the table (e.g. box drawing, accented chars). */",
        f"static const uint8_t font8x16_replacement[{fh}] = {{",
        "        0x00, 0x00, 0x7e, 0x42, 0x42, 0x42, 0x42, 0x42,",
        "        0x42, 0x42, 0x42, 0x42, 0x7e, 0x00, 0x00, 0x00,",
        "};",
        "",
    ]
    open(out, "w").write("\n".join(lines))
    if missing:
        print("warning: missing glyphs:", [hex(c) for c in missing], file=sys.stderr)
    print(f"wrote {out}: {LAST - FIRST + 1} glyphs at {fw}x{fh}")


main()
